=== camila-lopez08/Examen/libros.dtd
<?xml version="1.0" enconding="ISO-8859-1"?>
<!DOCTYPE listalibros SYSTEM  "libros1.xml">
        <!ELEMENT listalibros (portada|libro)*>
        <!ATTLIST listalibros
                nombre CDATA #REQUIRED
                centro CDATA #REQUIRED>
        <!ELEMENT portada (#PCDATA)>
        <!ATTLIST portada
                imagen CDATA #REQUIRED>
        <!ELEMENT libro (titulo|portada|autor|editorial|precio|codigo)*>
        <!ATTLIST libro
                anyo CDATA #REQUIRED>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT autor (apellido+,nombre+,cedula+,correo?|telefono?|Pais?|residencia?|ciudad?)>
                cedula CDATA #REQUIRED>
        <!ATTLIST autor
                foto CDATA #IMPLIED>
        <!ELEMENT apellido (#PCDATA)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT cedula (#PCDATA)>
        <!ELEMENT correo (#PCDATA)>
        <!ELEMENT telefono (#PCDATA)>
        <!ELEMENT Pais (#PCDATA)>
        <!ELEMENT residencia (#PCDATA)>
        <!ELEMENT ciudad (#PCDATA)>
        <!ELEMENT editorial (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        <!ELEMENT codigo (#PCDATA)>
        ]

=== camila-lopez08/Examen/libros1.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="libros.xsl"?>
<!DOCTYPE listalibros SYSTEM  "libros.dtd">
<listalibros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="libros.xsd"
             nombre="TomÃ¡s Carrasquilla" centro="poblado">
    <libro anyo="1994">
        <titulo>TCP/IP Illustrated</titulo>
        <autor foto="https://crearmiempresa.es/wp-content/uploads/2015/07/frases-de-steve-jobs.jpg">
                <nombre>W.</nombre>
                <cedula>1001138477</cedula>
                <correo>stevens@gmail.com</correo>
                <telefono>3013188632</telefono>
                <Pais>Colombia</Pais>
                <residencia>Buenos Aires</residencia>
                <ciudad>Bogota</ciudad>
        </autor>
        <editorial>Addison-Wesley</editorial>
        <precio>65.95</precio>
        <codigo>ESP</codigo>
    </libro>
    <libro anyo="1992">
        <titulo>Advanced Programming for Unix environment</titulo>
        <autor>
            <apellido>stevens</apellido>
            <nombre>W.</nombre>
            <cedula>1000872026</cedula>
        </autor>
        <editorial>Addison-Wesley</editorial>
        <precio>65.95</precio>
        <codigo>ESP</codigo>
    </libro>
    <libro anyo="2000">
        <titulo>Data on the Web</titulo>
        <autor>
            <apellido>abitebou</apellido>
            <nombre>Serge</nombre>
            <cedula>100235968</cedula>
        </autor>
        <autor>
            <apellido>buneman</apellido>
            <nombre>Peter</nombre>
            <cedula>1001138566</cedula>
        </autor>
        <autor>
            <apellido>suciu</apellido>
            <nombre>Dan</nombre>
            <cedula>432088856</cedula>
        </autor>
        <editorial>Morgan Kaufmann editorials</editorial>
        <precio>39.95</precio>
        <codigo>ESP</codigo>
    </libro>
    <libro anyo="1999">
        <titulo> Economics of Technology for Digital TV</titulo>
        <autor>
            <apellido>gerbar</apellido>
            <nombre>Darcy</nombre>
            <cedula>1000875632</cedula>
        </autor>
        <editorial>Kluwer Academic editorials</editorial>
        <precio>129.95</precio>
        <codigo>ESP</codigo>
    </libro>
</listalibros>
